namespace Gneedle.Psect;

// ReSharper disable InconsistentNaming
[SuppressMessage("ReSharper", "IdentifierTypo")]
public readonly struct ARM64() : IEnumerable<ARM64.Instruction>
{
    private readonly List<Instruction> m_Instructions = [];

    public void Add(byte opc, byte ope) => m_Instructions.Add(new Instruction
    {
        OpCode   = opc,
        Operands = [ope]
    });

    public void Add(byte opc, byte ope1, byte ope2) => m_Instructions.Add(new Instruction
    {
        OpCode   = opc,
        Operands = [ope1, ope2]
    });

    public void Add(byte opc, byte ope1, byte ope2, byte ope3) => m_Instructions.Add(new Instruction
    {
        OpCode   = opc,
        Operands = [ope1, ope2, ope3]
    });

    public void Add(byte opc, byte ope1, byte ope2, byte ope3, byte ope4) => m_Instructions.Add(new Instruction
    {
        OpCode   = opc,
        Operands = [ope1, ope2, ope3, ope4]
    });

    public List<Instruction>.Enumerator GetEnumerator() => m_Instructions.GetEnumerator();

    IEnumerator<Instruction> IEnumerable<Instruction>.GetEnumerator() => m_Instructions.GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => m_Instructions.GetEnumerator();

    public struct Instruction
    {
        public byte   OpCode;
        public byte[] Operands;
    }

    /// <summary>
    /// ARM64 register unique identifier.
    /// </summary>
    public enum REG
    {
        INVALID = 0,
        X29,
        X30,
        NZCV,
        SP,
        WSP,
        WZR,
        XZR,
        B0,
        B1,
        B2,
        B3,
        B4,
        B5,
        B6,
        B7,
        B8,
        B9,
        B10,
        B11,
        B12,
        B13,
        B14,
        B15,
        B16,
        B17,
        B18,
        B19,
        B20,
        B21,
        B22,
        B23,
        B24,
        B25,
        B26,
        B27,
        B28,
        B29,
        B30,
        B31,
        D0,
        D1,
        D2,
        D3,
        D4,
        D5,
        D6,
        D7,
        D8,
        D9,
        D10,
        D11,
        D12,
        D13,
        D14,
        D15,
        D16,
        D17,
        D18,
        D19,
        D20,
        D21,
        D22,
        D23,
        D24,
        D25,
        D26,
        D27,
        D28,
        D29,
        D30,
        D31,
        H0,
        H1,
        H2,
        H3,
        H4,
        H5,
        H6,
        H7,
        H8,
        H9,
        H10,
        H11,
        H12,
        H13,
        H14,
        H15,
        H16,
        H17,
        H18,
        H19,
        H20,
        H21,
        H22,
        H23,
        H24,
        H25,
        H26,
        H27,
        H28,
        H29,
        H30,
        H31,
        Q0,
        Q1,
        Q2,
        Q3,
        Q4,
        Q5,
        Q6,
        Q7,
        Q8,
        Q9,
        Q10,
        Q11,
        Q12,
        Q13,
        Q14,
        Q15,
        Q16,
        Q17,
        Q18,
        Q19,
        Q20,
        Q21,
        Q22,
        Q23,
        Q24,
        Q25,
        Q26,
        Q27,
        Q28,
        Q29,
        Q30,
        Q31,
        S0,
        S1,
        S2,
        S3,
        S4,
        S5,
        S6,
        S7,
        S8,
        S9,
        S10,
        S11,
        S12,
        S13,
        S14,
        S15,
        S16,
        S17,
        S18,
        S19,
        S20,
        S21,
        S22,
        S23,
        S24,
        S25,
        S26,
        S27,
        S28,
        S29,
        S30,
        S31,
        W0,
        W1,
        W2,
        W3,
        W4,
        W5,
        W6,
        W7,
        W8,
        W9,
        W10,
        W11,
        W12,
        W13,
        W14,
        W15,
        W16,
        W17,
        W18,
        W19,
        W20,
        W21,
        W22,
        W23,
        W24,
        W25,
        W26,
        W27,
        W28,
        W29,
        W30,
        X0,
        X1,
        X2,
        X3,
        X4,
        X5,
        X6,
        X7,
        X8,
        X9,
        X10,
        X11,
        X12,
        X13,
        X14,
        X15,
        X16,
        X17,
        X18,
        X19,
        X20,
        X21,
        X22,
        X23,
        X24,
        X25,
        X26,
        X27,
        X28,
        V0,
        V1,
        V2,
        V3,
        V4,
        V5,
        V6,
        V7,
        V8,
        V9,
        V10,
        V11,
        V12,
        V13,
        V14,
        V15,
        V16,
        V17,
        V18,
        V19,
        V20,
        V21,
        V22,
        V23,
        V24,
        V25,
        V26,
        V27,
        V28,
        V29,
        V30,
        V31,
        IP0 = X16,
        IP1 = X17,
        FP  = X29,
        LR  = X30
    }

    /// <summary>
    /// ARM64 address translation operation.
    /// </summary>
    public enum AT
    {
        INVALID = 0,
        S1E1R,
        S1E1W,
        S1E0R,
        S1E0W,
        S1E2R,
        S1E2W,
        S12E1R,
        S12E1W,
        S12E0R,
        S12E0W,
        S1E3R,
        S1E3W
    }

    /// <summary>
    /// ARM64 barrier operation.
    /// </summary>
    public enum BARRIER
    {
        INVALID = 0,
        OSHLD   = 0x1,
        OSHST   = 0x2,
        OSH     = 0x3,
        NSHLD   = 0x5,
        NSHST   = 0x6,
        NSH     = 0x7,
        ISHLD   = 0x9,
        ISHST   = 0xa,
        ISH     = 0xb,
        LD      = 0xd,
        ST      = 0xe,
        SY      = 0xf
    }

    /// <summary>
    /// ARM64 condition code.
    /// </summary>
    public enum CON
    {
        INVALID = 0,
        EQ,
        NE,
        HS,
        LO,
        MI,
        PL,
        VS,
        VC,
        HI,
        LS,
        GE,
        LT,
        GT,
        LE,
        AL,
        NV,
    }

    /// <summary>
    /// RM64 data cache operation.
    /// </summary>
    public enum DC
    {
        INVALID = 0,
        ZVA,
        IVAC,
        ISW,
        CVAC,
        CSW,
        CVAU,
        CIVAC,
        CISW
    }

    /// <summary>
    /// ARM64 extend operation.
    /// </summary>
    public enum EXT
    {
        INVALID = 0,
        UXTB,
        UXTH,
        UXTW,
        UXTX,
        SXTB,
        SXTH,
        SXTW,
        SXTX
    }

    /// <summary>
    /// ARM64 instruction cache operation.
    /// </summary>
    public enum IC
    {
        INVALID = 0,
        IALLUIS,
        IALLU,
        IVAU
    }

    /// <summary>
    /// ARM64 instruction group unique identifier.
    /// </summary>
    public enum GRP
    {
        INVALID = 0,
        JUMP,
        CALL,
        RET,
        INT,
        PRIVILEGE = 6,
        BRANCH_RELATIVE,
        CRYPTO = 128,
        FPARMV8,
        NEON,
        CRC
    }

    /// <summary>
    /// ARM64 instruction unique identifier.
    /// </summary>
    public enum INS
    {
        INVALID = 0,
        ABS,
        ADC,
        ADDHN,
        ADDHN2,
        ADDP,
        ADD,
        ADDV,
        ADR,
        ADRP,
        AESD,
        AESE,
        AESIMC,
        AESMC,
        AND,
        ASR,
        B,
        BFM,
        BIC,
        BIF,
        BIT,
        BL,
        BLR,
        BR,
        BRK,
        BSL,
        CBNZ,
        CBZ,
        CCMN,
        CCMP,
        CLREX,
        CLS,
        CLZ,
        CMEQ,
        CMGE,
        CMGT,
        CMHI,
        CMHS,
        CMLE,
        CMLT,
        CMTST,
        CNT,
        MOV,
        CRC32B,
        CRC32CB,
        CRC32CH,
        CRC32CW,
        CRC32CX,
        CRC32H,
        CRC32W,
        CRC32X,
        CSEL,
        CSINC,
        CSINV,
        CSNEG,
        DCPS1,
        DCPS2,
        DCPS3,
        DMB,
        DRPS,
        DSB,
        DUP,
        EON,
        EOR,
        ERET,
        EXTR,
        EXT,
        FABD,
        FABS,
        FACGE,
        FACGT,
        FADD,
        FADDP,
        FCCMP,
        FCCMPE,
        FCMEQ,
        FCMGE,
        FCMGT,
        FCMLE,
        FCMLT,
        FCMP,
        FCMPE,
        FCSEL,
        FCVTAS,
        FCVTAU,
        FCVT,
        FCVTL,
        FCVTL2,
        FCVTMS,
        FCVTMU,
        FCVTNS,
        FCVTNU,
        FCVTN,
        FCVTN2,
        FCVTPS,
        FCVTPU,
        FCVTXN,
        FCVTXN2,
        FCVTZS,
        FCVTZU,
        FDIV,
        FMADD,
        FMAX,
        FMAXNM,
        FMAXNMP,
        FMAXNMV,
        FMAXP,
        FMAXV,
        FMIN,
        FMINNM,
        FMINNMP,
        FMINNMV,
        FMINP,
        FMINV,
        FMLA,
        FMLS,
        FMOV,
        FMSUB,
        FMUL,
        FMULX,
        FNEG,
        FNMADD,
        FNMSUB,
        FNMUL,
        FRECPE,
        FRECPS,
        FRECPX,
        FRINTA,
        FRINTI,
        FRINTM,
        FRINTN,
        FRINTP,
        FRINTX,
        FRINTZ,
        FRSQRTE,
        FRSQRTS,
        FSQRT,
        FSUB,
        HINT,
        HLT,
        HVC,
        INS,
        ISB,
        LD1,
        LD1R,
        LD2R,
        LD2,
        LD3R,
        LD3,
        LD4,
        LD4R,
        LDARB,
        LDARH,
        LDAR,
        LDAXP,
        LDAXRB,
        LDAXRH,
        LDAXR,
        LDNP,
        LDP,
        LDPSW,
        LDRB,
        LDR,
        LDRH,
        LDRSB,
        LDRSH,
        LDRSW,
        LDTRB,
        LDTRH,
        LDTRSB,
        LDTRSH,
        LDTRSW,
        LDTR,
        LDURB,
        LDUR,
        LDURH,
        LDURSB,
        LDURSH,
        LDURSW,
        LDXP,
        LDXRB,
        LDXRH,
        LDXR,
        LSL,
        LSR,
        MADD,
        MLA,
        MLS,
        MOVI,
        MOVK,
        MOVN,
        MOVZ,
        MRS,
        MSR,
        MSUB,
        MUL,
        MVNI,
        NEG,
        NOT,
        ORN,
        ORR,
        PMULL2,
        PMULL,
        PMUL,
        PRFM,
        PRFUM,
        RADDHN,
        RADDHN2,
        RBIT,
        RET,
        REV16,
        REV32,
        REV64,
        REV,
        ROR,
        RSHRN2,
        RSHRN,
        RSUBHN,
        RSUBHN2,
        SABAL2,
        SABAL,
        SABA,
        SABDL2,
        SABDL,
        SABD,
        SADALP,
        SADDLP,
        SADDLV,
        SADDL2,
        SADDL,
        SADDW2,
        SADDW,
        SBC,
        SBFM,
        SCVTF,
        SDIV,
        SHA1C,
        SHA1H,
        SHA1M,
        SHA1P,
        SHA1SU0,
        SHA1SU1,
        SHA256H2,
        SHA256H,
        SHA256SU0,
        SHA256SU1,
        SHADD,
        SHLL2,
        SHLL,
        SHL,
        SHRN2,
        SHRN,
        SHSUB,
        SLI,
        SMADDL,
        SMAXP,
        SMAXV,
        SMAX,
        SMC,
        SMINP,
        SMINV,
        SMIN,
        SMLAL2,
        SMLAL,
        SMLSL2,
        SMLSL,
        SMOV,
        SMSUBL,
        SMULH,
        SMULL2,
        SMULL,
        SQABS,
        SQADD,
        SQDMLAL,
        SQDMLAL2,
        SQDMLSL,
        SQDMLSL2,
        SQDMULH,
        SQDMULL,
        SQDMULL2,
        SQNEG,
        SQRDMULH,
        SQRSHL,
        SQRSHRN,
        SQRSHRN2,
        SQRSHRUN,
        SQRSHRUN2,
        SQSHLU,
        SQSHL,
        SQSHRN,
        SQSHRN2,
        SQSHRUN,
        SQSHRUN2,
        SQSUB,
        SQXTN2,
        SQXTN,
        SQXTUN2,
        SQXTUN,
        SRHADD,
        SRI,
        SRSHL,
        SRSHR,
        SRSRA,
        SSHLL2,
        SSHLL,
        SSHL,
        SSHR,
        SSRA,
        SSUBL2,
        SSUBL,
        SSUBW2,
        SSUBW,
        ST1,
        ST2,
        ST3,
        ST4,
        STLRB,
        STLRH,
        STLR,
        STLXP,
        STLXRB,
        STLXRH,
        STLXR,
        STNP,
        STP,
        STRB,
        STR,
        STRH,
        STTRB,
        STTRH,
        STTR,
        STURB,
        STUR,
        STURH,
        STXP,
        STXRB,
        STXRH,
        STXR,
        SUBHN,
        SUBHN2,
        SUB,
        SUQADD,
        SVC,
        SYSL,
        SYS,
        TBL,
        TBNZ,
        TBX,
        TBZ,
        TRN1,
        TRN2,
        UABAL2,
        UABAL,
        UABA,
        UABDL2,
        UABDL,
        UABD,
        UADALP,
        UADDLP,
        UADDLV,
        UADDL2,
        UADDL,
        UADDW2,
        UADDW,
        UBFM,
        UCVTF,
        UDIV,
        UHADD,
        UHSUB,
        UMADDL,
        UMAXP,
        UMAXV,
        UMAX,
        UMINP,
        UMINV,
        UMIN,
        UMLAL2,
        UMLAL,
        UMLSL2,
        UMLSL,
        UMOV,
        UMSUBL,
        UMULH,
        UMULL2,
        UMULL,
        UQADD,
        UQRSHL,
        UQRSHRN,
        UQRSHRN2,
        UQSHL,
        UQSHRN,
        UQSHRN2,
        UQSUB,
        UQXTN2,
        UQXTN,
        URECPE,
        URHADD,
        URSHL,
        URSHR,
        URSQRTE,
        URSRA,
        USHLL2,
        USHLL,
        USHL,
        USHR,
        USQADD,
        USRA,
        USUBL2,
        USUBL,
        USUBW2,
        USUBW,
        UZP1,
        UZP2,
        XTN2,
        XTN,
        ZIP1,
        ZIP2,
        MNEG,
        UMNEGL,
        SMNEGL,
        NOP,
        YIELD,
        WFE,
        WFI,
        SEV,
        SEVL,
        NGC,
        SBFIZ,
        UBFIZ,
        SBFX,
        UBFX,
        BFI,
        BFXIL,
        CMN,
        MVN,
        TST,
        CSET,
        CINC,
        CSETM,
        CINV,
        CNEG,
        SXTB,
        SXTH,
        SXTW,
        CMP,
        UXTB,
        UXTH,
        UXTW,
        IC,
        DC,
        AT,
        TLBI,
        NEGS,
        NGCS
    }

    /// <summary>
    /// ARM64 MRS system register.
    /// </summary>
    public enum MRS
    {
        INVALID           = 0,
        MDCCSR_EL0        = 0x9808,
        DBGDTRRX_EL0      = 0x9828,
        MDRAR_EL1         = 0x8080,
        OSLSR_EL1         = 0x808c,
        DBGAUTHSTATUS_EL1 = 0x83f6,
        PMCEID0_EL0       = 0xdce6,
        PMCEID1_EL0       = 0xdce7,
        MIDR_EL1          = 0xc000,
        CCSIDR_EL1        = 0xc800,
        CLIDR_EL1         = 0xc801,
        CTR_EL0           = 0xd801,
        MPIDR_EL1         = 0xc005,
        REVIDR_EL1        = 0xc006,
        AIDR_EL1          = 0xc807,
        DCZID_EL0         = 0xd807,
        ID_PFR0_EL1       = 0xc008,
        ID_PFR1_EL1       = 0xc009,
        ID_DFR0_EL1       = 0xc00a,
        ID_AFR0_EL1       = 0xc00b,
        ID_MMFR0_EL1      = 0xc00c,
        ID_MMFR1_EL1      = 0xc00d,
        ID_MMFR2_EL1      = 0xc00e,
        ID_MMFR3_EL1      = 0xc00f,
        ID_ISAR0_EL1      = 0xc010,
        ID_ISAR1_EL1      = 0xc011,
        ID_ISAR2_EL1      = 0xc012,
        ID_ISAR3_EL1      = 0xc013,
        ID_ISAR4_EL1      = 0xc014,
        ID_ISAR5_EL1      = 0xc015,
        ID_A64PFR0_EL1    = 0xc020,
        ID_A64PFR1_EL1    = 0xc021,
        ID_A64DFR0_EL1    = 0xc028,
        ID_A64DFR1_EL1    = 0xc029,
        ID_A64AFR0_EL1    = 0xc02c,
        ID_A64AFR1_EL1    = 0xc02d,
        ID_A64ISAR0_EL1   = 0xc030,
        ID_A64ISAR1_EL1   = 0xc031,
        ID_A64MMFR0_EL1   = 0xc038,
        ID_A64MMFR1_EL1   = 0xc039,
        MVFR0_EL1         = 0xc018,
        MVFR1_EL1         = 0xc019,
        MVFR2_EL1         = 0xc01a,
        RVBAR_EL1         = 0xc601,
        RVBAR_EL2         = 0xe601,
        RVBAR_EL3         = 0xf601,
        ISR_EL1           = 0xc608,
        CNTPCT_EL0        = 0xdf01,
        CNTVCT_EL0        = 0xdf02,
        TRCSTATR          = 0x8818,
        TRCIDR8           = 0x8806,
        TRCIDR9           = 0x880e,
        TRCIDR10          = 0x8816,
        TRCIDR11          = 0x881e,
        TRCIDR12          = 0x8826,
        TRCIDR13          = 0x882e,
        TRCIDR0           = 0x8847,
        TRCIDR1           = 0x884f,
        TRCIDR2           = 0x8857,
        TRCIDR3           = 0x885f,
        TRCIDR4           = 0x8867,
        TRCIDR5           = 0x886f,
        TRCIDR6           = 0x8877,
        TRCIDR7           = 0x887f,
        TRCOSLSR          = 0x888c,
        TRCPDSR           = 0x88ac,
        TRCDEVAFF0        = 0x8bd6,
        TRCDEVAFF1        = 0x8bde,
        TRCLSR            = 0x8bee,
        TRCAUTHSTATUS     = 0x8bf6,
        TRCDEVARCH        = 0x8bfe,
        TRCDEVID          = 0x8b97,
        TRCDEVTYPE        = 0x8b9f,
        TRCPIDR4          = 0x8ba7,
        TRCPIDR5          = 0x8baf,
        TRCPIDR6          = 0x8bb7,
        TRCPIDR7          = 0x8bbf,
        TRCPIDR0          = 0x8bc7,
        TRCPIDR1          = 0x8bcf,
        TRCPIDR2          = 0x8bd7,
        TRCPIDR3          = 0x8bdf,
        TRCCIDR0          = 0x8be7,
        TRCCIDR1          = 0x8bef,
        TRCCIDR2          = 0x8bf7,
        TRCCIDR3          = 0x8bff,
        ICC_IAR1_EL1      = 0xc660,
        ICC_IAR0_EL1      = 0xc640,
        ICC_HPPIR1_EL1    = 0xc662,
        ICC_HPPIR0_EL1    = 0xc642,
        ICC_RPR_EL1       = 0xc65b,
        ICH_VTR_EL2       = 0xe659,
        ICH_EISR_EL2      = 0xe65b,
        ICH_ELSR_EL2      = 0xe65d
    }

    /// <summary>
    /// ARM64 MSR system register.
    /// </summary>
    public enum MSR
    {
        INVALID        = 0,
        DBGDTRTX_EL0   = 0x9828,
        OSLAR_EL1      = 0x8084,
        PMSWINC_EL0    = 0xdce4,
        TRCOSLAR       = 0x8884,
        TRCLAR         = 0x8be6,
        ICC_EOIR1_EL1  = 0xc661,
        ICC_EOIR0_EL1  = 0xc641,
        ICC_DIR_EL1    = 0xc659,
        ICC_SGI1R_EL1  = 0xc65d,
        ICC_ASGI1R_EL1 = 0xc65e,
        ICC_SGI0R_EL1  = 0xc65f
    }

    /// <summary>
    /// ARM64 prefetch operation.
    /// </summary>
    public enum PRFM
    {
        INVALID   = 0,
        PLDL1KEEP = 0x00 + 1,
        PLDL1STRM = 0x01 + 1,
        PLDL2KEEP = 0x02 + 1,
        PLDL2STRM = 0x03 + 1,
        PLDL3KEEP = 0x04 + 1,
        PLDL3STRM = 0x05 + 1,
        PLIL1KEEP = 0x08 + 1,
        PLIL1STRM = 0x09 + 1,
        PLIL2KEEP = 0x0a + 1,
        PLIL2STRM = 0x0b + 1,
        PLIL3KEEP = 0x0c + 1,
        PLIL3STRM = 0x0d + 1,
        PSTL1KEEP = 0x10 + 1,
        PSTL1STRM = 0x11 + 1,
        PSTL2KEEP = 0x12 + 1,
        PSTL2STRM = 0x13 + 1,
        PSTL3KEEP = 0x14 + 1,
        PSTL3STRM = 0x15 + 1
    }

    /// <summary>
    /// ARM64 shift operation.
    /// </summary>
    public enum SFT
    {
        INVALID = 0,
        LSL,
        MSL,
        LSR,
        ASR,
        ROR
    }

    /// <summary>
    /// ARM64 processor state field.
    /// </summary>
    public enum PSTATE
    {
        INVALID              = 0,
        ARM64_PSTATE_SPSEL   = 0x05,
        ARM64_PSTATE_DAIFSET = 0x1e,
        ARM64_PSTATE_DAIFCLR = 0x1f
    }

    /// <summary>
    /// ARM64 translation lookaside buffer operation.
    /// </summary>
    public enum TLBI
    {
        INVALID = 0,
        VMALLE1IS,
        VAE1IS,
        ASIDE1IS,
        VAAE1IS,
        VALE1IS,
        VAALE1IS,
        ALLE2IS,
        VAE2IS,
        ALLE1IS,
        VALE2IS,
        VMALLS12E1IS,
        ALLE3IS,
        VAE3IS,
        VALE3IS,
        IPAS2E1IS,
        IPAS2LE1IS,
        IPAS2E1,
        IPAS2LE1,
        VMALLE1,
        VAE1,
        ASIDE1,
        VAAE1,
        VALE1,
        VAALE1,
        ALLE2,
        VAE2,
        ALLE1,
        VALE2,
        VMALLS12E1,
        ALLE3,
        VAE3,
        VALE3
    }

    /// <summary>
    /// ARM64 vector arrangement specifier.
    /// </summary>
    public enum VAS
    {
        INVALID = 0,
        _8B,
        _16B,
        _4H,
        _8H,
        _2S,
        _4S,
        _1D,
        _2D,
        _1Q
    }

    /// <summary>
    /// ARM64 vector element size specifier.
    /// </summary>
    public enum VESS
    {
        INVALID = 0,
        B,
        H,
        S,
        D
    }
}