<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Gneedle.Aspect</RootNamespace>
        <NuSpecFile>Gneedle.Aspect.nuspec</NuSpecFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <TargetFrameworks>net5.0;netstandard2.1;</TargetFrameworks>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <AspectOutPath Condition="$(MSBuildRuntimeType) == 'Core'">$(MSBuildThisFileDirectory)bin\$(Configuration)\netstandard2.1</AspectOutPath>
        <AspectTargetPath>$(AspectOutPath)\Gneedle.Aspect.dll</AspectTargetPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Build" Version="17.6.3"/>
        <PackageReference Include="Microsoft.Build.Tasks.Core" Version="17.11.4"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Inject\Source\Gneedle.Inject.csproj" />
    </ItemGroup>

    <Target Name="SetNuspecProperties" BeforeTargets="GenerateNuspec">
        <PropertyGroup>
            <NuspecProperties>id=$(MSBuildProjectName);authors=$(Authors);version=$(PackageVersion);configuration=$(Configuration);</NuspecProperties>
        </PropertyGroup>
    </Target>

    <UsingTask TaskName="$(ProjectName).AddProjectsPostBuild" AssemblyFile="$(AspectTargetPath)"/>
    <Target Name="SolutionScan" AfterTargets="PostBuildEvent" Condition="Exists('$(AspectTargetPath)')">
        <AddProjectsPostBuild ProjectName="$(ProjectName)" SolutionPath="$(SolutionPath)" TargetPath="$(AspectTargetPath)"/>
    </Target>
</Project>